version: '3.8'

services:
  app:
    build: .
    container_name: fastapi_app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=${SQLALCHEMY_DATABASE_URL}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000,http://localhost:8081
      - ENV=development
    depends_on:
      - redis

  redis:
    image: redis:7.0.12
    container_name: redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
