##This commented code is to be used in test environment on your laptop locally
# version: '3.8'

# networks:
#   app_network:
#     driver: bridge

# services:
#   redis:
#     image: redis:7.0.12
#     container_name: redis
#     ports:
#       - "6380:6379"  # Change the host port to 6380
#     networks:
#       - app_network
#     volumes:
#       - redis_data:/data
#     restart: always

#   fastapi_app:
#     build: .
#     container_name: fastapi_app
#     command: gunicorn app.main:app --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --workers 2  --threads 2 --timeout 1001 --keep-alive 1001  

#     volumes:
#       - .:/app
#     env_file:
#       - .env
#     ports:
#       - "8000:8000"  # Exposing FastAPI on port 8000
#     environment:
#       - REDIS_HOST=redis  # Use the Docker service name "redis"
#       - REDIS_PORT=6379
#     depends_on:
#       - redis
#     networks:
#       - app_network
#     restart: always

#   nginx_proxy:
#     image: nginx:1.23-alpine
#     container_name: nginx_proxy
#     depends_on:
#       - fastapi_app
#     ports:
#       - "80:80"  # Exposing Nginx on port 80
#     volumes: 
#       - ./visis-backend/visis-app/nginx.conf:/etc/nginx/nginx.conf:ro
#       - ./visis-backend/visis-app/static:/usr/share/nginx/html/static:ro
#     networks:
#       - app_network
#     restart: always

# volumes:
#   redis_data:


version: '3.8'

networks:
  app_network:
    driver: bridge

services:
  redis:
    image: redis:7.0.12
    container_name: redis
    ports:
      - "6380:6379"  # Change the host port to 6380
    networks:
      - app_network
    volumes:
      - redis_data:/data
    restart: always

  fastapi_app:
    # build: .
    image: adesojialu/visiszipnov26_app:latest  # Use the Docker Hub image
    container_name: fastapi_app
    command: gunicorn app.main:app --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --workers 2 --threads 2 --timeout 1001 --keep-alive 1001
    # volumes:
    #   - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"  # Exposing FastAPI on port 8000
    environment:
      - REDIS_HOST=redis  # Use the Docker service name "redis"
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_CACHE_TTL=80640
    depends_on:
      - redis
    networks:
      - app_network
    restart: always

  nginx_proxy:
    image: nginx:1.23-alpine
    container_name: nginx_proxy
    depends_on:
      - fastapi_app
    ports:
      - "80:80"  # Exposing Nginx on port 80
    volumes:
      - ./visis-app/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./visis-app/static:/usr/share/nginx/html/static:ro
    networks:
      - app_network
    restart: always

volumes:
  redis_data:
