name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository (optional if you need code context)
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install SSH client if needed (usually available by default)
      - name: Ensure SSH is installed
        run: sudo apt-get update && sudo apt-get install -y ssh

      # Connect to EC2 and run Docker Compose
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          # Change to your app directory, pull the latest image, and restart using docker-compose
          script: |
            cd /home/ubuntu/app
            # Pull the latest image from registry
            docker-compose pull
            
            # (Optional) Stop currently running containers if needed
            docker-compose down
            
            # Rebuild and run in detached mode
            docker-compose up -d --build
            
            # Optional: Check logs or status
            docker-compose ps
